kind: Service
apiVersion: v1
metadata:
  name: hello-world-nextjs-svc
  labels:
    app: hello-world-nextjs
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80              # The port that the service listens on
      targetPort: 3000      # The port that your container exposes
  selector:
    app: hello-world-nextjs  # Ensure this matches the Deployment's labels
  type: ClusterIP            # Change to NodePort or LoadBalancer if external access is needed


